# Lecture4  - データの取得と操作 -
<div dir='rtl'>
2023.4岩政
</div>

このJupyter notebookは第４回目のスライドに乗っているコードを再現したものです。スライドと合わせて動作を行わせて確認してください。

特にpythonコードに説明は付けていませんが、スライドの説明を参照のこと。

最初に https://raw.githubusercontent.com/miwamasa/DataScience2022/main/notebooks/data/fortune500.csv

を ローカルディスクにコピーします（ここではtmpフォルダの下にfortune500.csvとして保存します)

https://raw.githubusercontent.com/miwamasa/DataScience2022/main/notebooks/data/fortune500.csv
をブラウザで開けて、右クリックで「名前を付けて保存」でPCのローカルディスクにコピーします。

## Recap
ファイルのアップロードの仕方が少しわかりにくかったのでもう一度おさらいします。
- ファイルをアップロードする
  - Colab画面の左にある「ファイル」アイコンをクリックするとフォルダ構成画面が表示する
  - フォルダ構成画面の上方に、「セッションストレージにアップロード」アイコンをクリックし、ファイルを選択する
  - フォルダ画面にアップロードしたファイルが見えることを確認
  - notebookのコードcellからファイルにアクセスできるようになる。
- ファイルを次に残したい場合
  - Colabではセッションが終了すると、アップロードしたファイルは消える（セッションに再接続してみえることもある）
  - ファイルを次のセッション（翌日起動など）に残したい場合は、Google DriveをマウントしてGoogle Driveにファイルをアップロードすると使える。
## Google Driveのマウント
### フォルダ構造を表示
- ドライブにnotebookをコピーした後
- 左のバーにあるフォルダのアイコンをクリックすると、フォルダ構成が表示されます。

<img src="figures/lec2_colab_drive0.png" width="50%">

### ドライブをマウント
- 「ドライブをマウント」ボタンを押すと、notebookにマウントを行うcellが挿入される


<img src="figures/lec2_colab_drive1.png" width="50%">

- cellを実行すると、'drive'がマウントされて、ファイル構造に反映される

<img src="figures/lec2_colab_drive2.png" width="50%">

#### ファイルをアップロード
- Chromeの新しいタブを開き、GoogleメニューからGoogle Driveを開きます。
- 最初にローカルPCに保存したfortune500.csvを「マイドライブ」の直下にアップロードします
- 右クリックで「ファイルをアップロード」を選択してファイルアップロードします

<img src="figures/lec2_colab_drive3.png" width="50%">

- ファイルがアップロードされたことを確認します。

<img src="figures/lec2_colab_drive4.png" width="50%">

- Colabに戻ると、ファイル構成に'fortune500.csv'が反映されてます。

<img src="figures/lec2_colab_drive5.png" width="50%">

#### ファイルパスを修正してファイル読み込みのcellを実行

<img src="figures/lec2_colab_drive6.png" width="50%">

それではやってみましょう。

In [ ]:
# csvパッケージを使う場合
import csv
filename = 'data/fortune500.csv'
with open(filename, encoding='utf8', newline='') as f:
    csvreader = csv.reader(f)
    for row in csvreader:
        print(row)

In [ ]:
# pandasパッケージを使う場合
import pandas as pd
df = pd.read_csv('data/fortune500.csv')
df.head()

## numpyとndarray
pythonのnumpyパッケージ付属のn次元配列を生成するクラス
- 同じ型しか格納できない、型が決まっている＝安全
- 多次元配列を表現できる
- 数値計算のためのメソッド・関数が豊富で、高速な演算が可能


In [1]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
print('type(x):',type(x),'x.shape:',x.shape,'x.dtype:',x.dtype)

type(x): <class 'numpy.ndarray'> x.shape: (2, 3) x.dtype: float64


numpyのloadtext、savetextの例

In [2]:
import numpy as np
a=np.array([[2,3,4],[5,6,7],[8,9,10]])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [3]:
np.savetxt('test.txt', a)

ファイルを読み込みます。

In [13]:
np.loadtxt('test.txt')

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

## Pandas
- DataFrameを作る（値のリストのリストから作る、コラムの辞書から作る）

In [14]:
import pandas as pd # pandasをpdとしてインポートします
# Defining DataFrame by specifing a list of observations
df_1= pd.DataFrame([['a', 'b', 'c'], # リスト（１行分）のリスト（行数分）
                 ['d', 'e', 'f'],
                 ['g', 'h', 'i']],
                index = [1,2,3], columns = ['col1', 'col2', 'col3'])
# Defining DataFrame by specifing a dictionary of columns 
df_2= pd.DataFrame({'col1': ['a', 'd', 'g'], #コラム名と一列文のリスト
                 'col2': ['b', 'e', 'h'],
                 'col3': ['c', 'f', 'i']}, 
                 index = [1,2,3])

In [15]:
df_1

col1 col2 col3
1    a    b    c
2    d    e    f
3    g    h    i

In [16]:
df_2

col1 col2 col3
1    a    b    c
2    d    e    f
3    g    h    i

### csvからDataFrameを読む(read_csv関数の利用)
- 例）時刻をインデクスとしてもつテーブルをcsvファイルから読み込む例
  - 時刻(テキスト)をdatetimeオブジェクトに変換しながら読み込む

最初にデータ(foo.csv)を準備します。ここではnumpyを使って作ります。

In [37]:
import pandas as pd
import numpy as np

# DataFrameの作成
dates = pd.date_range('2022-01-01', periods=5)
items = ['apple', 'banana', 'orange', 'grape', 'kiwi']
expenses = np.random.randint(1, 10, size=5)
days = [date.day_name() for date in dates]  # 日付から曜日を生成
df = pd.DataFrame({'Date': dates, 'Day': days, 'Item': items, 'Expense': expenses})

# CSVファイルとして保存
df.to_csv('foo.csv', index=False)

ファイルの中身を表示します

In [42]:
with open('foo.csv', 'r') as f:
    print(f.read())

Date,Day,Item,Expense
2022-01-01,Saturday,apple,1
2022-01-02,Sunday,banana,8
2022-01-03,Monday,orange,2
2022-01-04,Tuesday,grape,2
2022-01-05,Wednesday,kiwi,4



pandasのread_csvを使って、dataframeに読み込みます。

In [43]:
import pandas as pd
df=pd.read_csv('foo.csv',index_col='Date',parse_dates=['Date'],
      encoding='SHIFT-JIS',names=('Date','Day','Item','Expense'))

In [44]:
df

Day    Item  Expense
Date                                  
Date              Day    Item  Expense
2022-01-01   Saturday   apple        1
2022-01-02     Sunday  banana        8
2022-01-03     Monday  orange        2
2022-01-04    Tuesday   grape        2
2022-01-05  Wednesday    kiwi        4

In [45]:
iris=pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/iris.csv')
iris

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

### 要素の選択：行、列による指定

- loc:コラム名を使って要素を選択、df.loc[行インデックス,列名]
- iloc:自然数インデクスを使って要素を選択、df.iloc[行番号,列番号]

In [46]:
iris.loc[[0,1]] # ラベル0,1のみを得る 

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa

In [47]:
iris.iloc[1:4,0:3] # 行がindex=1から3まで、列が0から3までを抽出

SepalLength  SepalWidth  PetalLength
1          4.9         3.0          1.4
2          4.7         3.2          1.3
3          4.6         3.1          1.5

### 列や行の一部を取り出す
- 行の取り出し：条件抽出、head/tail、列の取り出し：コラム名、正規表現


### DataFrameの結合の例
- ２つのDataFrameをマージします。
- 入力とする２つのDataFrameを作ります

In [49]:
df_1 = iris.iloc[[1,51],3:]
df_2= iris.iloc[[1,51,101],[0,2,4]]

howにouterを指定するとonで示す列に対し、どちらか片方に存在するキーも使われます(例ではon='Name'

In [50]:
pd.merge(df_1, df_2, how = 'outer', on= 'Name')

PetalWidth             Name  SepalLength  PetalLength
0         0.2      Iris-setosa          4.9          1.4
1         1.5  Iris-versicolor          6.4          4.5
2         NaN   Iris-virginica          5.8          5.1

howにinnerを指定するとonで示す列に対し、両方のデータに存在するキーのみで構成されます(例ではon='Name')

In [51]:
pd.merge(df_1, df_2, how = 'inner', on= 'Name')


PetalWidth             Name  SepalLength  PetalLength
0         0.2      Iris-setosa          4.9          1.4
1         1.5  Iris-versicolor          6.4          4.5

### 時系列データ
- 時系列データを生成する
  - 2000年1月1日を開始時刻として、nobs=8か月（freqは周期、'M':毎月末)

In [52]:
nobs=8
ts=pd.date_range('1/1/2000',periods=nobs,freq='M')

In [53]:
ts

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
               '2000-05-31', '2000-06-30', '2000-07-31', '2000-08-31'],
              dtype='datetime64[ns]', freq='M')

- 時間インデクスを使った列(Series)のスライスの例

In [56]:
# 時系列データをインデクスとしてSeriesを作成
y0=np.random.normal(loc=1.5,scale=2.0, size=nobs)
y= pd.Series(y0,index=ts)
y

2000-01-31    2.006081
2000-02-29    1.398428
2000-03-31    0.437373
2000-04-30    3.361943
2000-05-31    3.169883
2000-06-30   -1.836041
2000-07-31    4.670882
2000-08-31    0.380442
Freq: M, dtype: float64

In [57]:
y['31/3/2000':'31/7/2000']

2000-03-31    0.437373
2000-04-30    3.361943
2000-05-31    3.169883
2000-06-30   -1.836041
2000-07-31    4.670882
Freq: M, dtype: float64

## ndarrayとDataFrame間の変換

numpyのndarray型は、配列ですが、
- 同じ型しか格納できない
- 多次元配列を表現できる
- 数値計算のためのメソッド・関数が豊富で、高速な演算が可能


In [86]:
#numpy.ndarrayを作ります。
x=np.random.normal(size=10)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[-0.5570355   0.6871087  -1.09815912 -0.81382826  0.06581122 -0.48595727
 -0.17525581 -0.95657848  1.64751688 -0.59823148]


In [87]:
#一端、pandasのSeries型に変換します。
y=pd.Series(x)
print(type(y))
print(y)

<class 'pandas.core.series.Series'>
0   -0.557035
1    0.687109
2   -1.098159
3   -0.813828
4    0.065811
5   -0.485957
6   -0.175256
7   -0.956578
8    1.647517
9   -0.598231
dtype: float64


In [88]:
# dataframeにします。
df=pd.DataFrame(x)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0
0 -0.557035
1  0.687109
2 -1.098159
3 -0.813828
4  0.065811
5 -0.485957
6 -0.175256
7 -0.956578
8  1.647517
9 -0.598231

カラム名をつけます

In [89]:
# dataframeにするときに Head,Tailの２つのカラムを作ります。
df=pd.DataFrame({'Head':x,'Tail':x*2})
df

Head      Tail
0 -0.557035 -1.114071
1  0.687109  1.374217
2 -1.098159 -2.196318
3 -0.813828 -1.627657
4  0.065811  0.131622
5 -0.485957 -0.971915
6 -0.175256 -0.350512
7 -0.956578 -1.913157
8  1.647517  3.295034
9 -0.598231 -1.196463

列をえるには、カラム名を指定します。

In [84]:
df['Head']

0    0.700095
1    1.415208
2   -1.227657
3    1.507893
4   -0.726513
5    0.402385
6   -0.809334
7   -0.721048
8    0.224616
9    1.365862
Name: Head, dtype: float64

arrayに戻すには、valuesを使います。

In [85]:
df['Head'].values

array([ 0.70009548,  1.41520775, -1.22765709,  1.50789333, -0.72651332,
        0.40238482, -0.80933354, -0.72104809,  0.22461647,  1.36586237])

#### データの統計的な概要を表示するdescribe()

In [68]:
iris=pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/iris.csv')
iris.describe()

SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

### グループ化
goupebyメソッドは指定したコラムの値が同じもので、列をグループ化します。

In [71]:
df_3 = iris.iloc[[1,2,3,4,51,52,53,54],[0,2,4]]
a=df_3.groupby('Name')
a

In [70]:
#例えば、'Name'コラムが'Iris-versicolor'であるものの部分DataFrameをえるにはget_groupを使います。
a.get_group('Iris-versicolor')

SepalLength  PetalLength             Name
51          6.4          4.5  Iris-versicolor
52          6.9          4.9  Iris-versicolor
53          5.5          4.0  Iris-versicolor
54          6.5          4.6  Iris-versicolor

### マルチインデクス

In [73]:
df_2 = pd.DataFrame(np.arange(16).reshape(4,4), 
                 index = [['A', 'A', 'B', 'B'],['a','b','c','d']],         
                 columns = ['boston','newyork','london','tokyo'])
df_2.index.names = ['Idx1', 'Idx2']
df_2

boston  newyork  london  tokyo
Idx1 Idx2                                
A    a          0        1       2      3
     b          4        5       6      7
B    c          8        9      10     11
     d         12       13      14     15

### 値でないものはNaN(非数Not a Number)、np.nanを用いる

In [74]:
df_na_1 = pd.DataFrame([[1, 2, 3, 4], 
                     [4, 5, 6, np.nan], 
                     [6, np.nan, 7, 8], 
                     [9, np.nan, np.nan, np.nan]])
df_na_1.dropna() 

0    1    2    3
0  1  2.0  3.0  4.0

#### メソッドチェーン
最初に普通に

- 最初に3列のDataFrameを作成し
- 次に、pd.melt()関数を使用して、DataFrameの形式を変更し
- その後、rename()メソッドを使用して列名を変更し、
- query()メソッドを使用して、val列が200以上の行を抽出しています。

In [79]:
import pandas as pd

# DataFrameの作成
df = pd.DataFrame({'A': [1, 2, 3], 'B': [400, 500, 600], 'C': [7, 800, 900]})
print('元のデータフレーム:\n', df)

# データフレームの形式を変更
df = pd.melt(df).rename(columns={'variable': 'var', 'value': 'val'})
print('形式変更後のデータフレーム:\n', df)

# valが200以上の行を抽出
df = df.query('val >= 200')
print('valが200以上の行を抽出したデータフレーム:\n', df)


元のデータフレーム:
    A    B    C
0  1  400    7
1  2  500  800
2  3  600  900
形式変更後のデータフレーム:
   var  val
0   A    1
1   A    2
2   A    3
3   B  400
4   B  500
5   B  600
6   C    7
7   C  800
8   C  900
valが200以上の行を抽出したデータフレーム:
   var  val
3   B  400
4   B  500
5   B  600
7   C  800
8   C  900


これをメソッドチェーンでやると

In [80]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [400, 500, 600], 'C': [7, 800, 900]})
print('元のデータフレーム:\n', df)

df = (pd.melt(df)
        .rename(columns={
                'variable' : 'var',  
                'value' : 'val'})
        .query('val >= 200')
     )
df

元のデータフレーム:
    A    B    C
0  1  400    7
1  2  500  800
2  3  600  900


var  val
3   B  400
4   B  500
5   B  600
7   C  800
8   C  900

## Pandas クイズ
ここでは、Pandasに関するクイズを2つ紹介します。

クイズ１： dfというデータフレームがあり、col1とcol2という列があります。col1列が[1, 2, 3]でcol2列が[4, 5, 6]である場合、以下のコードは何を出力しますか？

```python
df['col3'] = df.apply(lambda row: row['col1'] + row['col2'], axis=1)
print(df)
```

In [94]:
#やってみましょう。
df=pd.DataFrame({"col1":[1, 2, 3],"col2":[4, 5, 6]})

クイズ２：
次のようなdataframeがあります。


```python
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [4, 5, 6, 7], 'C': [7, 8, 9, 10]})
```

つぎは何になりますか？
```
print(df.iloc[1:3, 0:2])
```

In [95]:
#やってみましょう

クイズ３：次のようなデータフレームdfがあります。

```python
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [4, 5, 6, 7], 'C': [7, 8, 9, 10]})
```

つぎは何になりますか？

```
print(df.loc[df['B'] > 5])
```

In [98]:
#やってみましょう